### ISSUE TITLE
Client ergonomics improvements

### ISSUE THREAD

**Issue by rferreira** [uvasoftware/scanii-java#64]
The client should accept an auth token for credentials, right now we need to pass a empty string: 

```java
var oneShotClient = ScaniiClients.createDefault(target, authToken.getResourceId(), "", httpClient);
```

**Comment by rferreira** [comment]
delete auth token should return a boolean

**Comment by rferreira** [comment]
404 on accounts is not properly handled 
```
ERROR c.s.a.monitoring.ApiSpecV21Monitor - Resource: [/v2.1/account.json] FAILED
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at com.uvasoftware.scanii.impl.ErrorExtractor.extract(ErrorExtractor.java:7)
	at com.uvasoftware.scanii.impl.DefaultScaniiClient.parseAndThrowError(DefaultScaniiClient.java:419)
	at com.uvasoftware.scanii.impl.DefaultScaniiClient.lambda$retrieveAccountInfo$8(DefaultScaniiClient.java:375)
	at com.amazonaws.xray.proxies.apache.http.TracedResponseHandler.handleResponse(TracedResponseHandler.java:70)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at com.amazonaws.xray.proxies.apache.http.TracedHttpClient.lambda$execute$4(TracedHttpClient.java:210)
	at com.amazonaws.xray.proxies.apache.http.TracedHttpClient.wrapHttpSupplier(TracedHttpClient.java:133)
	at com.amazonaws.xray.proxies.apache.http.TracedHttpClient.execute(TracedHttpClient.java:207)
	at com.uvasoftware.scanii.impl.DefaultScaniiClient.retrieveAccountInfo(DefaultScaniiClient.java:371)
	at com.scanii.agent.monitoring.ApiSpecV21Monitor.lambda$run$5(ApiSpecV21Monitor.java:155)
	at com.scanii.agent.monitoring.ApiSpecV21Monitor.lambda$run$6(ApiSpecV21Monitor.java:176)
	at com.amazonaws.xray.entities.Entity.run(Entity.java:53)
	at com.amazonaws.xray.entities.Entity.run(Entity.java:43)
	at com.scanii.agent.monitoring.ApiSpecV21Monitor.lambda$run$7(ApiSpecV21Monitor.java:172)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
